environment:
  name: prod
  project: cdf-bootcamp-67-prod
  validation-type: prod
  selected:
  - modules/bootcamp/data_foundation
  - modules/bootcamp/ice_cream_api
  - modules/bootcamp/use_cases/oee

variables:
  modules:
    bootcamp:
      # Variables shared by modules
      icapi_ds_external_id: ds_icapi
      icapi_space_name: icapi_dm_space
      data_foundation:
        data_developer_source_id: dbaa2f63-3a54-451e-9f17-c0e064ec0525 # Group object ID of the data developer group
      ice_cream_api:
        icapi_extractors_source_id: a3224b2a-a408-4510-bb34-18b29ecdb5af # Group object ID of the extractor entra group
        tokenUri: ${IDP_TOKEN_URL}
        cdfProjectName: ${CDF_PROJECT}
        scopes: ${IDP_SCOPES}
        icapi_trigger_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_trigger_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}
        icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}
      data_set_external_id: ds_ice_cream_factory
      oee_data_set_external_id: ds_oee

      use_cases:
        oee:
          data_pipeline_oee_source_id: a982db0f-71f6-4208-9f6b-617d14dafe74
          uc_oee_ds_external_id: ds_uc_oee
          oee_space_name: oee_ts_space
          data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID}
          data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET}
